# Generated by Django 4.0.3 on 2022-04-04 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='nombre',
            field=models.CharField(default='', max_length=50),
        ),
    ]
